### ISSUE TITLE
metagenomic data normalization method used in ML

### ISSUE THREAD

**Issue by zhq90** [DMnBI/MDL4Microbiome#1]
I am about to use MDL4Microbiome to construct a machine learning model. I have noticed that there many data normalization methods like Fraction, TMM, CLR, ALR ... . I totally confused which normalization method should I use to input to  MDL4Microbiome.
Would you have some recommendations about data normalization methods for ML?

**Comment by withJack** [comment]
Hi, 
In the paper, I used log transformation method for normalization. The formula for log transformation I used is as follows: 
***x' = log2(x+1)***, where x is the original data and x' is the transformed data. 

I cannot give you a definite answer which normalization method best fits your data. I recommend you to try different methods and see the results. 

Thanks, 
Seung Jae Lee
